project:
  type: book

book:
  title: "NEPHU First Nations Population Profile"
  chapters:
    - index.qmd
    - part: "1. Introduction"
    - part: "2. Methods - Data Analysis"
    - part: "3. Methods - Consultation"
    - part: "4. Population"
      chapters: 
        - chapters/04a_population_size.qmd
    - part: "5. Demographics"
    - part: "6. Socioeconomic Determinants of Health"
    - part: "7. Cultural Determinants of Health"
    - part: "8. Other Determinants of Health"
    - part: "9. Health Promoting and Risk Behaviours"
      chapters:
        - chapters/09a_preventive_healthyeating_example.qmd
        - chapters/09b_preventive_physicalactivity_example.qmd
    - part: "10. Health Consequences"
    - references.qmd

bibliography: references.bib

format:
  html:
    embed-resources: false
    css: styles.css
    html-table-processing: none
    fig-align: center
    fig-cap-location: top
    grid: 
      body-width: 1000px
    number-sections: false
    toc: true
    toc-location: right
    toc-depth: 3
  pdf:
    documentclass: scrreprt

execute: 
  echo: false
  warning: false
  error: false
  global: "setup.R"

