project:
  type: book

book:
  title: "Gumunatj Ngarrngatj:<br>The NEPHU First Nations Population Profile"
  chapters:
    - index.qmd
    - part: "1. Introduction"
    - part: "2. Methods - Data Analysis"
    - part: "3. Methods - Consultation"
    - part: "4. Population"
      chapters: 
        - chapters/04a_population_size.qmd
        - chapters/04b_population_growth.qmd
    - part: "5. Demographics"
      chapters: 
        - chapters/05a_demographics_agesex.qmd
        - chapters/05b_demographics_language.qmd
    - part: "6. Socioeconomic Determinants of Health"
      chapters:
        - chapters/06a_socioeconomic_perinatal.qmd
        - chapters/06b_socioeconomic_childhood.qmd
        - chapters/06c_socioeconomic_education.qmd
        - chapters/06d_socioeconomic_employment.qmd
        - chapters/06e_socioeconomic_income.qmd
        - chapters/06f_socioeconomic_housing.qmd
    - part: "7. Cultural Determinants of Health"
      chapters: 
        - chapters/07a_cultural_connection.qmd
        - chapters/07b_cultural_country.qmd
    - part: "8. Other Determinants of Health"
      chapters: 
        - chapters/08a_other_justice.qmd
        - chapters/08b_other_childprotection.qmd
        - chapters/08c_other_familysafety.qmd
        - chapters/08d_other_discrimination.qmd
        - chapters/08e_other_digitalinclusion.qmd
        - chapters/08f_other_healthservices.qmd
    - part: "9. Health and Wellbeing Practices"
      chapters: 
        - chapters/09a_preventive_healthyeating.qmd
        - chapters/09b_preventive_physicalactivity.qmd
        - chapters/09c_preventive_tobacco.qmd
        - chapters/09d_preventive_alcoholdrugs.qmd
        - chapters/09e_preventive_biomedical.qmd
        - chapters/09f_preventive_vaccination.qmd
        - chapters/09g_preventive_screening.qmd
    - part: "10. Health Outcomes"
      chapters: 
        - chapters/10a_consequences_general.qmd
        - chapters/10b_consequences_disability.qmd
        - chapters/10c_consequences_arthritis.qmd
        - chapters/10d_consequences_asthma.qmd
        - chapters/10e_consequences_cancer.qmd
        - chapters/10f_consequences_diabetes.qmd
        - chapters/10g_consequences_cardiovascular.qmd
        - chapters/10h_consequences_kidney.qmd
        - chapters/10i_consequences_lung.qmd
        - chapters/10j_consequences_other.qmd
        - chapters/10k_consequences_infectious.qmd
        - chapters/10l_consequences_mentalhealth.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    embed-resources: false
    css: styles.css
    html-table-processing: none
    fig-align: center
    fig-cap-location: top
    grid: 
      body-width: 1000px
    number-sections: false
    anchor-sections: false
    toc: true
    toc-location: right
    toc-depth: 3
  pdf:
    documentclass: scrreprt

execute: 
  echo: false
  warning: false
  error: false
  cache: false

